// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheBigThree.Data;

#nullable disable

namespace TheBigThree.Migrations
{
    [DbContext(typeof(TheBigThreeDbContext))]
    [Migration("20260312114552_AddApplicationUserWithAvatar")]
    partial class AddApplicationUserWithAvatar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TheBigThree.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "48668352-3932-411a-966a-123456789012",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "484b5d74-6f70-49fd-a94f-4ab382ce570f",
                            Email = "geralt@kaermorhen.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "GERALT@KAERMORHEN.COM",
                            NormalizedUserName = "GERALTOFRIVIA",
                            PasswordHash = "AQAAAAIAAYagAAAAENyuOQQHg81q9bOGPytlxE7IuCs6Og7ccOil7KrLFIfRcCZpDayvshkpi2e0gIfLGQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4be95166-69ff-42a2-9b53-5289663d83e3",
                            TwoFactorEnabled = false,
                            UserName = "GeraltOfRivia"
                        },
                        new
                        {
                            Id = "7c13958c-362c-4493-979d-098765432109",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a7b929c2-a21d-4848-b393-5418d5157a3c",
                            Email = "shepard@normandy.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SHEPARD@NORMANDY.COM",
                            NormalizedUserName = "COMMANDERSHEPARD",
                            PasswordHash = "AQAAAAIAAYagAAAAECpDr0nq+zhg9xdRAQ4D3HaaXjCVvLoHHeVH5oN1gq3Y0IuRwt6HQcjh3e7KbxffxQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fffebb95-806a-428e-9c5d-4d008554555d",
                            TwoFactorEnabled = false,
                            UserName = "CommanderShepard"
                        },
                        new
                        {
                            Id = "a1b2c3d4-1111-2222-3333-aabbccdd0001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "319b40c1-15f0-4786-86eb-4d71f565d0f8",
                            Email = "snake@shadowmoses.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SNAKE@SHADOWMOSES.COM",
                            NormalizedUserName = "SOLIDSNAKE",
                            PasswordHash = "AQAAAAIAAYagAAAAEJfjZWQn8jGj713VPpI7tAded2S6DOcjXFK2ax62IsvfWNjJAY8xZt+V+VcLzhNFrg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "14dac4fa-f68d-41f4-9515-dcb7bf2e5f6b",
                            TwoFactorEnabled = false,
                            UserName = "SolidSnake"
                        },
                        new
                        {
                            Id = "a1b2c3d4-1111-2222-3333-aabbccdd0002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2ee5978b-841b-4e62-bbfe-ac1243946cb4",
                            Email = "chief@unsc.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CHIEF@UNSC.COM",
                            NormalizedUserName = "MASTERCHIEF",
                            PasswordHash = "AQAAAAIAAYagAAAAEGTPuV0cLw/uPQVTshcZICcxTXVg8PXl5vIR5o68StmWYbiNjT1+f5JuRRg4PlbTAA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9a2cd622-2358-4272-a356-a2bb49651d92",
                            TwoFactorEnabled = false,
                            UserName = "MasterChief"
                        },
                        new
                        {
                            Id = "a1b2c3d4-1111-2222-3333-aabbccdd0003",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c25197dc-3a13-466e-8fca-581e95d3db06",
                            Email = "arthur@dutchgang.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ARTHUR@DUTCHGANG.COM",
                            NormalizedUserName = "ARTHURMORGAN",
                            PasswordHash = "AQAAAAIAAYagAAAAEGgTZQ6cx3No9lUFp2cJVyvy+Y5IdEUxgaQLfISip81gqTvQ0XDSEIsVeNmmZMZCzA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "56277386-9919-4b6c-8dfc-65c7970cabad",
                            TwoFactorEnabled = false,
                            UserName = "ArthurMorgan"
                        },
                        new
                        {
                            Id = "a1b2c3d4-1111-2222-3333-aabbccdd0004",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d23b9492-1d62-4d78-a7ad-a80917f6d45f",
                            Email = "lara@croftmanor.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "LARA@CROFTMANOR.COM",
                            NormalizedUserName = "LARACROFT",
                            PasswordHash = "AQAAAAIAAYagAAAAEIYgAstLz0Iyb5RJ9DAF9opqsRSODL1pXXIntkGvyEplKCk2Kx3RGIAFGS9iSKBaKg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7f677d2b-5470-4869-8c98-9ecd5ee7f093",
                            TwoFactorEnabled = false,
                            UserName = "LaraCroft"
                        },
                        new
                        {
                            Id = "a1b2c3d4-1111-2222-3333-aabbccdd0005",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ea9e207d-8da3-4fc3-8d8b-e955f858700e",
                            Email = "aloy@horizon.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ALOY@HORIZON.COM",
                            NormalizedUserName = "ALOYHORIZON",
                            PasswordHash = "AQAAAAIAAYagAAAAEPorByYSE+b8Naz3db5j9mBpOl4RG1Hf9DAh9CBfD+gaBN0rwmE5MXqpIOgMOMQi2g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6f12e795-14b5-4b51-8e2e-e57eccf7cffe",
                            TwoFactorEnabled = false,
                            UserName = "AloyHorizon"
                        });
                });

            modelBuilder.Entity("TheBigThree.Data.Models.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalStars")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Collections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2026, 2, 25, 11, 45, 52, 71, DateTimeKind.Utc).AddTicks(1519),
                            Title = "Masterpieces of Atmosphere",
                            TotalStars = 5,
                            UserId = "48668352-3932-411a-966a-123456789012"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2026, 2, 28, 11, 45, 52, 71, DateTimeKind.Utc).AddTicks(1533),
                            Title = "Sci-Fi and Soul",
                            TotalStars = 3,
                            UserId = "7c13958c-362c-4493-979d-098765432109"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2026, 3, 2, 11, 45, 52, 71, DateTimeKind.Utc).AddTicks(1534),
                            Title = "Stealth Legends",
                            TotalStars = 8,
                            UserId = "a1b2c3d4-1111-2222-3333-aabbccdd0001"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2026, 3, 4, 11, 45, 52, 71, DateTimeKind.Utc).AddTicks(1536),
                            Title = "Shooters That Defined a Generation",
                            TotalStars = 12,
                            UserId = "a1b2c3d4-1111-2222-3333-aabbccdd0002"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2026, 3, 6, 11, 45, 52, 71, DateTimeKind.Utc).AddTicks(1537),
                            Title = "Open World Masterpieces",
                            TotalStars = 15,
                            UserId = "a1b2c3d4-1111-2222-3333-aabbccdd0003"
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2026, 3, 9, 11, 45, 52, 71, DateTimeKind.Utc).AddTicks(1539),
                            Title = "Indie Gems Worth Your Time",
                            TotalStars = 3,
                            UserId = "a1b2c3d4-1111-2222-3333-aabbccdd0004"
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2026, 3, 11, 11, 45, 52, 71, DateTimeKind.Utc).AddTicks(1540),
                            Title = "Horror That Kept Me Up at Night",
                            TotalStars = 7,
                            UserId = "a1b2c3d4-1111-2222-3333-aabbccdd0005"
                        });
                });

            modelBuilder.Entity("TheBigThree.Data.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CollectionId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("TheBigThree.Data.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CollectionId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("GenreId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CollectionId = 1,
                            Description = "The Witcher 3: Wild Hunt is a genre-defining open-world RPG that sets a monumental standard for narrative depth and world-building. Following the journey of Geralt of Rivia, the game weaves a complex tapestry of political intrigue, personal loss, and mythical horror. Every side quest feels like a handcrafted story, often presenting morally grey choices that ripple throughout the Continent, ensuring that no two playthroughs ever feel exactly the same.",
                            GenreId = 3,
                            ImageUrl = "/images/seed/witcher3.jpg",
                            Title = "The Witcher 3"
                        },
                        new
                        {
                            Id = 2,
                            CollectionId = 1,
                            Description = "Elden Ring is a masterclass in environmental storytelling and player agency, born from the legendary collaboration between FromSoftware and George R.R. Martin. The Lands Between offers an unparalleled sense of discovery, where every horizon hides a secret, a challenge, or a piece of haunting lore. Its combat system is deep and rewarding, allowing for endless build variety while maintaining the signature 'tough but fair' difficulty that defines the Soulslike genre.",
                            GenreId = 19,
                            ImageUrl = "/images/seed/eldenring.jpg",
                            Title = "Elden Ring"
                        },
                        new
                        {
                            Id = 3,
                            CollectionId = 1,
                            Description = "Silent Hill 2 remains the gold standard for psychological horror, utilizing atmosphere and symbolism to explore the darkest corners of the human psyche. The journey of James Sunderland is not merely a survival horror experience but a deeply personal exploration of guilt, punishment, and redemption. Supported by Akira Yamaoka's legendary score and an oppressive fog that conceals grotesque manifestations of trauma, it is a game that haunts the player long after the credits roll.",
                            GenreId = 8,
                            ImageUrl = "/images/seed/silenthill2.jpg",
                            Title = "Silent Hill 2"
                        },
                        new
                        {
                            Id = 4,
                            CollectionId = 2,
                            Description = "The original Dark Souls is a landmark achievement in level design, featuring a world that is intricately interconnected in ways that still baffle and delight players today. It revitalized the concept of discovery through trial and error, punishing recklessness while rewarding patience and observation. From the heights of Anor Londo to the depths of Blighttown, its somber atmosphere and cryptic lore created a legacy that spawned an entire sub-genre of modern action-RPGs.",
                            GenreId = 19,
                            ImageUrl = "/images/seed/darksouls.jpg",
                            Title = "Dark Souls"
                        },
                        new
                        {
                            Id = 5,
                            CollectionId = 2,
                            Description = "Mass Effect 2 represents the pinnacle of squad-based storytelling, focusing on the assembly of a diverse team of specialists for a high-stakes suicide mission against the Collectors. The game expertly balances fast-paced tactical combat with profound character interactions, where loyalty missions provide deep insight into your companions' pasts. The choices made by Commander Shepard carry immense weight, culminating in a finale that remains one of the most intense and emotional sequences in gaming history.",
                            GenreId = 3,
                            ImageUrl = "/images/seed/masseffect2.jpg",
                            Title = "Mass Effect 2"
                        },
                        new
                        {
                            Id = 6,
                            CollectionId = 2,
                            Description = "Cyberpunk 2077 offers a breathtakingly dense vision of a dystopian future within the neon-soaked sprawl of Night City. Playing as V, players navigate a dangerous world of corporate warfare, cybernetic enhancement, and mercenary survival. The narrative is a deeply personal one, exploring themes of identity and legacy alongside the digital ghost of Johnny Silverhand. With its vastly improved systems and immersive first-person perspective, it delivers a uniquely visceral and stylish RPG experience.",
                            GenreId = 3,
                            ImageUrl = "/images/seed/cyberpunk2077.jpg",
                            Title = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = 7,
                            CollectionId = 3,
                            Description = "Metal Gear Solid 3: Snake Eater is a masterpiece of stealth game design set against the backdrop of the Cold War. Following the mission of Naked Snake deep in the Soviet jungle, the game introduces a survival and camouflage system that demands creative thinking and patience. Its emotionally devastating finale remains one of the most impactful moments in gaming history, cementing Big Boss as one of the medium's greatest tragic heroes.",
                            GenreId = 14,
                            ImageUrl = "/images/seed/mgs3.jpg",
                            Title = "Metal Gear Solid 3"
                        },
                        new
                        {
                            Id = 8,
                            CollectionId = 3,
                            Description = "Dishonored is a brilliantly designed immersive sim that places player agency above all else. As Corvo Attano, a supernatural assassin framed for murder, the game offers a staggering variety of approaches to every encounter — from ghost-like pacifist runs to chaotic high-power takedowns. Its Victorian-industrial city of Dunwall is one of gaming's most atmospheric settings, dripping with political intrigue and dark lore.",
                            GenreId = 14,
                            ImageUrl = "/images/seed/dishonored.jpg",
                            Title = "Dishonored"
                        },
                        new
                        {
                            Id = 9,
                            CollectionId = 3,
                            Description = "Hitman: Blood Money represents the peak of the sandbox assassination formula. Each level is an intricately designed puzzle box filled with creative opportunities to eliminate targets in increasingly elaborate ways. The game rewards patience, observation, and improvisation, allowing Agent 47 to blend seamlessly into any environment. Its iconic missions and darkly comedic tone make it an enduring classic of the stealth genre.",
                            GenreId = 14,
                            ImageUrl = "/images/seed/hitman.jpg",
                            Title = "Hitman: Blood Money"
                        },
                        new
                        {
                            Id = 10,
                            CollectionId = 4,
                            Description = "Halo 2 fundamentally changed what was expected of a console first-person shooter. Its dual-wielding mechanics, switching narrative between Master Chief and the Arbiter, and the introduction of online multiplayer via Xbox Live created a template that the industry followed for years. The cliffhanger ending may have frustrated fans at the time, but the game's impact on competitive online gaming is still felt to this day.",
                            GenreId = 5,
                            ImageUrl = "/images/seed/halo2.jpg",
                            Title = "Halo 2"
                        },
                        new
                        {
                            Id = 11,
                            CollectionId = 4,
                            Description = "DOOM 2016 revitalized the first-person shooter genre by stripping away cover mechanics and regenerating health in favor of relentless, aggressive combat. The glory kill system encourages constant forward momentum, rewarding fearless play with health and ammo. Mick Gordon's iconic industrial metal soundtrack perfectly complements the non-stop carnage, making this one of the most purely satisfying shooters ever created.",
                            GenreId = 5,
                            ImageUrl = "/images/seed/doom2016.jpg",
                            Title = "DOOM (2016)"
                        },
                        new
                        {
                            Id = 12,
                            CollectionId = 4,
                            Description = "Counter-Strike: Global Offensive is the definitive competitive first-person shooter, refined over decades into a game of pure mechanical skill and tactical teamwork. Its economy system, precise gunplay, and iconic maps like Dust2 have created a competitive ecosystem unlike any other. The game demands absolute precision and communication, rewarding dedicated players with a depth of mastery that few shooters can match.",
                            GenreId = 5,
                            ImageUrl = "/images/seed/csgo.jpg",
                            Title = "Counter-Strike: Global Offensive"
                        },
                        new
                        {
                            Id = 13,
                            CollectionId = 5,
                            Description = "Red Dead Redemption 2 is Rockstar's magnum opus — a sprawling, painstakingly detailed portrait of the dying American frontier. Arthur Morgan's journey is one of the most emotionally resonant narratives in gaming, exploring themes of loyalty, redemption, and the inevitable march of progress. Every corner of its vast world feels handcrafted and alive, from chance encounters on muddy trails to the bustling streets of Saint Denis.",
                            GenreId = 16,
                            ImageUrl = "/images/seed/rdr2.jpg",
                            Title = "Red Dead Redemption 2"
                        },
                        new
                        {
                            Id = 14,
                            CollectionId = 5,
                            Description = "Breath of the Wild reinvented the open world genre by creating a world governed by consistent physical rules rather than scripted events. Every element of Hyrule can be interacted with, climbed, burned, or frozen, giving players unprecedented freedom to approach any situation creatively. Its philosophy of discovery over hand-holding restored a sense of childlike wonder to gaming that had been largely absent from big-budget titles for years.",
                            GenreId = 2,
                            ImageUrl = "/images/seed/botw.jpg",
                            Title = "The Legend of Zelda: Breath of the Wild"
                        },
                        new
                        {
                            Id = 15,
                            CollectionId = 5,
                            Description = "Grand Theft Auto V is an unprecedented achievement in open world design, featuring three interwoven protagonists navigating the sun-soaked excess and moral bankruptcy of Los Santos. Its heist missions represent some of the most ambitious set pieces in gaming history, while the living, breathing city remains a benchmark for environmental detail and emergent storytelling. The game's enduring popularity is a testament to the sheer density of its world.",
                            GenreId = 16,
                            ImageUrl = "/images/seed/gtav.jpg",
                            Title = "Grand Theft Auto V"
                        },
                        new
                        {
                            Id = 16,
                            CollectionId = 6,
                            Description = "Hollow Knight is a triumph of independent game development, delivering a vast and hauntingly beautiful underground kingdom filled with challenging combat, intricate platforming, and a melancholic lore told through environmental storytelling. Team Cherry's masterpiece rivals the best of the Metroidvania genre, offering dozens of hours of exploration across a world that constantly rewards curiosity and punishes complacency.",
                            GenreId = 18,
                            ImageUrl = "/images/seed/hollowknight.jpg",
                            Title = "Hollow Knight"
                        },
                        new
                        {
                            Id = 17,
                            CollectionId = 6,
                            Description = "Hades redefined what a roguelike could be by weaving a compelling narrative directly into its endlessly replayable structure. Each failed escape attempt from the Underworld advances the story and deepens relationships with a cast of brilliantly written mythological characters. Supergiant Games achieved something extraordinary — a game where dying feels as rewarding as succeeding, ensuring every run leaves the player hungry for one more attempt.",
                            GenreId = 17,
                            ImageUrl = "/images/seed/hades.jpg",
                            Title = "Hades"
                        },
                        new
                        {
                            Id = 18,
                            CollectionId = 6,
                            Description = "Celeste is a precision platformer that uses its brutally challenging gameplay as a metaphor for mental health struggles, delivering one of gaming's most sincere and affecting narratives. Madeline's climb up the titular mountain mirrors her internal battle with anxiety and self-doubt, creating a rare synergy between mechanics and story. Its tight controls and brilliantly designed levels make every hard-won summit feel like a genuine personal achievement.",
                            GenreId = 9,
                            ImageUrl = "/images/seed/celeste.jpg",
                            Title = "Celeste"
                        },
                        new
                        {
                            Id = 19,
                            CollectionId = 7,
                            Description = "The Resident Evil 2 Remake is a near-perfect reimagining of a survival horror classic, updating its fixed-camera predecessor into a tense over-the-shoulder nightmare without sacrificing any of the original's atmosphere or tension. The relentless pursuit of Mr. X creates a constant sense of dread that permeates every corridor of the Raccoon City Police Department. It stands as a blueprint for how to respectfully modernize a beloved classic.",
                            GenreId = 8,
                            ImageUrl = "/images/seed/re2remake.jpg",
                            Title = "Resident Evil 2 Remake"
                        },
                        new
                        {
                            Id = 20,
                            CollectionId = 7,
                            Description = "Amnesia: The Dark Descent stripped away combat entirely, leaving players with nothing but darkness, limited resources, and the terrifying sounds of pursuing monsters. Its sanity mechanic punishes even looking at threats for too long, creating a uniquely psychological horror experience. The game fundamentally changed the horror genre and inspired an entire generation of atmospheric, narrative-driven horror titles.",
                            GenreId = 8,
                            ImageUrl = "/images/seed/amnesia.jpg",
                            Title = "Amnesia: The Dark Descent"
                        },
                        new
                        {
                            Id = 21,
                            CollectionId = 7,
                            Description = "Outlast drops players into the nightmare of Mount Massive Asylum armed with nothing but a camcorder and their nerve. The absence of any combat mechanics transforms every encounter into pure flight-or-hide survival, creating sustained tension that few horror games have matched. Seen entirely through the grainy green glow of night vision, its corridors filled with disturbing imagery make it one of the most viscerally unsettling horror experiences in gaming.",
                            GenreId = 8,
                            ImageUrl = "/images/seed/outlast.jpg",
                            Title = "Outlast"
                        });
                });

            modelBuilder.Entity("TheBigThree.Data.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "RPG"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "First-Person Shooter"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Racing"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Platformer"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Simulation"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Fighting"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Puzzle"
                        },
                        new
                        {
                            Id = 13,
                            Name = "MMORPG"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Stealth"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Survival"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Action/Adventure"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Roguelike"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Metroidvania"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Soulslike"
                        });
                });

            modelBuilder.Entity("TheBigThree.Data.Models.Like", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CollectionId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "CollectionId");

                    b.HasIndex("CollectionId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TheBigThree.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TheBigThree.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBigThree.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TheBigThree.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheBigThree.Data.Models.Collection", b =>
                {
                    b.HasOne("TheBigThree.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheBigThree.Data.Models.Comment", b =>
                {
                    b.HasOne("TheBigThree.Data.Models.Collection", "Collection")
                        .WithMany("Comments")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheBigThree.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheBigThree.Data.Models.Game", b =>
                {
                    b.HasOne("TheBigThree.Data.Models.Collection", "Collection")
                        .WithMany("Games")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBigThree.Data.Models.Genre", "Genre")
                        .WithMany("Games")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("TheBigThree.Data.Models.Like", b =>
                {
                    b.HasOne("TheBigThree.Data.Models.Collection", "Collection")
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheBigThree.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheBigThree.Data.Models.Collection", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Games");
                });

            modelBuilder.Entity("TheBigThree.Data.Models.Genre", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
