// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheBigThree.Data;

#nullable disable

namespace TheBigThree.Migrations
{
    [DbContext(typeof(TheBigThreeDbContext))]
    [Migration("20260203072625_FinalLongSeed")]
    partial class FinalLongSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "48668352-3932-411a-966a-123456789012",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bafcfe9e-b0a2-47a7-b17e-2217c96f649c",
                            Email = "geralt@kaermorhen.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "GERALT@KAERMORHEN.COM",
                            NormalizedUserName = "GERALTOFRIVIA",
                            PasswordHash = "AQAAAAIAAYagAAAAECI3DvNrudh1T0lLAEw+gRfhXAcBVgNG+hTt6da5j5NyuHoEU2uGqnbK7CWITEY6Cw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4c176def-4b52-4c10-b605-f59e54bdc282",
                            TwoFactorEnabled = false,
                            UserName = "GeraltOfRivia"
                        },
                        new
                        {
                            Id = "7c13958c-362c-4493-979d-098765432109",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c118dcc4-9b3f-4493-96c7-c08b2f804047",
                            Email = "shepard@normandy.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SHEPARD@NORMANDY.COM",
                            NormalizedUserName = "COMMANDERSHEPARD",
                            PasswordHash = "AQAAAAIAAYagAAAAEGUyZwakLfIC7wZqfAbIIMB8eTNpuH2um+YnKor9nrg73PVLLwp78qq8e42KuGDAcA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f4a82053-59c8-4e82-ac8a-b04b34737dde",
                            TwoFactorEnabled = false,
                            UserName = "CommanderShepard"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TheBigThree.Models.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalStars")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Collections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2026, 1, 29, 7, 26, 25, 319, DateTimeKind.Utc).AddTicks(9855),
                            Title = "Masterpieces of Atmosphere",
                            TotalStars = 5,
                            UserId = "48668352-3932-411a-966a-123456789012"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2026, 2, 1, 7, 26, 25, 319, DateTimeKind.Utc).AddTicks(9860),
                            Title = "Sci-Fi and Soul",
                            TotalStars = 1,
                            UserId = "7c13958c-362c-4493-979d-098765432109"
                        });
                });

            modelBuilder.Entity("TheBigThree.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CollectionId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("GenreId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CollectionId = 1,
                            Description = "The Witcher 3: Wild Hunt is a genre-defining open-world RPG that sets a monumental standard for narrative depth and world-building. Following the journey of Geralt of Rivia, the game weaves a complex tapestry of political intrigue, personal loss, and mythical horror. Every side quest feels like a handcrafted story, often presenting morally grey choices that ripple throughout the Continent, ensuring that no two playthroughs ever feel exactly the same.",
                            GenreId = 3,
                            ImageUrl = "/images/seed/witcher3.jpg",
                            Title = "The Witcher 3"
                        },
                        new
                        {
                            Id = 2,
                            CollectionId = 1,
                            Description = "Elden Ring is a masterclass in environmental storytelling and player agency, born from the legendary collaboration between FromSoftware and George R.R. Martin. The Lands Between offers an unparalleled sense of discovery, where every horizon hides a secret, a challenge, or a piece of haunting lore. Its combat system is deep and rewarding, allowing for endless build variety while maintaining the signature 'tough but fair' difficulty that defines the Soulslike genre.",
                            GenreId = 19,
                            ImageUrl = "/images/seed/eldenring.jpg",
                            Title = "Elden Ring"
                        },
                        new
                        {
                            Id = 3,
                            CollectionId = 1,
                            Description = "Silent Hill 2 remains the gold standard for psychological horror, utilizing atmosphere and symbolism to explore the darkest corners of the human psyche. The journey of James Sunderland is not merely a survival horror experience but a deeply personal exploration of guilt, punishment, and redemption. Supported by Akira Yamaoka's legendary score and an oppressive fog that conceals grotesque manifestations of trauma, it is a game that haunts the player long after the credits roll.",
                            GenreId = 8,
                            ImageUrl = "/images/seed/silenthill2.jpg",
                            Title = "Silent Hill 2"
                        },
                        new
                        {
                            Id = 4,
                            CollectionId = 2,
                            Description = "The original Dark Souls is a landmark achievement in level design, featuring a world that is intricately interconnected in ways that still baffle and delight players today. It revitalized the concept of discovery through trial and error, punishing recklessness while rewarding patience and observation. From the heights of Anor Londo to the depths of Blighttown, its somber atmosphere and cryptic lore created a legacy that spawned an entire sub-genre of modern action-RPGs.",
                            GenreId = 19,
                            ImageUrl = "/images/seed/darksouls.jpg",
                            Title = "Dark Souls"
                        },
                        new
                        {
                            Id = 5,
                            CollectionId = 2,
                            Description = "Mass Effect 2 represents the pinnacle of squad-based storytelling, focusing on the assembly of a diverse team of specialists for a high-stakes suicide mission against the Collectors. The game expertly balances fast-paced tactical combat with profound character interactions, where loyalty missions provide deep insight into your companions' pasts. The choices made by Commander Shepard carry immense weight, culminating in a finale that remains one of the most intense and emotional sequences in gaming history.",
                            GenreId = 3,
                            ImageUrl = "/images/seed/masseffect2.jpg",
                            Title = "Mass Effect 2"
                        },
                        new
                        {
                            Id = 6,
                            CollectionId = 2,
                            Description = "Cyberpunk 2077 offers a breathtakingly dense vision of a dystopian future within the neon-soaked sprawl of Night City. Playing as V, players navigate a dangerous world of corporate warfare, cybernetic enhancement, and mercenary survival. The narrative is a deeply personal one, exploring themes of identity and legacy alongside the digital ghost of Johnny Silverhand. With its vastly improved systems and immersive first-person perspective, it delivers a uniquely visceral and stylish RPG experience.",
                            GenreId = 3,
                            ImageUrl = "/images/seed/cyberpunk2077.jpg",
                            Title = "Cyberpunk 2077"
                        });
                });

            modelBuilder.Entity("TheBigThree.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "RPG"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "First-Person Shooter"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Racing"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Platformer"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Simulation"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Fighting"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Puzzle"
                        },
                        new
                        {
                            Id = 13,
                            Name = "MMORPG"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Stealth"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Survival"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Action/Adventure"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Roguelike"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Metroidvania"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Soulslike"
                        });
                });

            modelBuilder.Entity("TheBigThree.Models.Like", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CollectionId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "CollectionId");

                    b.HasIndex("CollectionId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheBigThree.Models.Collection", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheBigThree.Models.Game", b =>
                {
                    b.HasOne("TheBigThree.Models.Collection", "Collection")
                        .WithMany("Games")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBigThree.Models.Genre", "Genre")
                        .WithMany("Games")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("TheBigThree.Models.Like", b =>
                {
                    b.HasOne("TheBigThree.Models.Collection", "Collection")
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheBigThree.Models.Collection", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("TheBigThree.Models.Genre", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
